# https://golangci-lint.run/usage/quick-start/
run:
  timeout: 1m
  build-tags:
linters:
# https://golangci-lint.run/usage/linters/

  enable:

    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    #- bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    #- depguard
    - dogsled
    - durationcheck
    #- dupword
    - errchkjson
    - err113
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    #- forbidigo
    #- forcetypeassert
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - err113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - grouper
    - importas
    - interfacebloat
    - intrange
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    #- nestif
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - stylecheck
    - sqlclosecheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - unconvert
    - unparam
    - usestdlibvars
    #- varnamelen
    - wastedassign
    - whitespace
    - wrapcheck


linters-settings:
  lll:
    line-length: 160
  cyclop:
    max-complexity: 25
issues:
  exclude-rules:
    - path: c2/sslshell/sslshellserver.go
      linters:
        - staticcheck
      text: SA1019
    - path: c2/httpservefile/httpservefile.go
      linters:
        - staticcheck
      text: SA1019
    - path: httphelper.go
      linters:
        - staticcheck
      text: SA1019
  exclude-files:
     - protocol/mikrotik/mikrotik_test.go
     - protocol/mikrotik/msg.go
     - protocol/rocketmq/remoting.go
     - protocol/payloads
     - cli/commandline_test.go
     - payload/wrapper_test.go
