# https://golangci-lint.run/usage/quick-start/
run:
  timeout: 1m
  skip-dirs:
  skip-files:
   - protocol/mikrotik/mikrotik_test.go
   - protocol/mikrotik/msg.go
   - protocol/rocketmq/remoting.go
   - protocol/payloads
  build-tags:
linters:
# https://golangci-lint.run/usage/linters/

  enable:

    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    #- bodyclose
    - containedctx
    #- contextcheck
    #- cyclop
    - decorder
    #- depguard
    - dogsled
    - durationcheck
    - dupword
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - grouper
    - importas
    - interfacebloat
    - lll
    - makezero
    - misspell
    - nakedret
    #- nestif
    - nilerr
    - nlreturn
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - stylecheck
    - tagliatelle
    - tenv
    - unconvert
    - unparam
    #- usestdlibvars
    #- varnamelen
    - wastedassign
    - whitespace
    - wrapcheck


linters-settings:
  gocritic:
    # Enable multiple checks by tags. See "Tags" section in https://github.com/go-critic/go-critic#usage.
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - emptyFallthrough
      - importShadow
      - unnamedResult
  lll:
    line-length: 140
issues:
  exclude-rules:
    - path: c2/sslshell/sslshellserver.go
      linters:
        - staticcheck
      text: SA1019
    - path: c2/httpservefile/httpservefile.go
      linters:
        - staticcheck
      text: SA1019
    - path: framework.go
      linters:
        - staticcheck
      text: SA1019